### ISSUE TITLE
Dark mode doesn't work in old ui illustration page

### ISSUE THREAD

**Issue by nobSEIFO** [CeuiLiSA/Pixiv-Shaft#636]
### Acknowledgements / 确认事项

- [X] I have updated to the latest version of the app / 已经更新到最新版
- [X] I have tried the FAQ / 试过FAQ了. [FAQ](https://github.com/CeuiLiSA/Pixiv-Shaft/blob/master/FAQ.md)
- [X] I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another issue / 搜索过其他issue，确实不是重复问题
- [X] I will fill out the title and the information in this template / 填好标题和内容

### Shaft app version

4.1.4

### Android system version

Android 8

### Device model

Samsung s7 

### Network information (if necessary) / 如果需要（无法看图之类），请提交网络信息

- [X] Can directly access to pixiv website / 可直接访问网页版pixiv
- [ ] Use proxy / 使用了代理
- [ ] Settings-Direct open enabled / 开启直连
- [X] Settings-Use pixivcat enabled / 开启使用pixivcat代理

### Steps to reproduce / 复现步骤

Open the app
Click on a photo

### Expected behavior / 期望行为

It should be in the dark mode (enabled in settings)
![Screenshot_20240812-212925_PixShaft](https://github.com/user-attachments/assets/d019a8ee-c34a-4104-b8b2-b8bfcf8f3108)
Tis is the light mode for reference
![Screenshot_20240812-213033_PixShaft](https://github.com/user-attachments/assets/5b4506bb-939d-4fce-b9ec-1f05fb0e71be)

### Actual behavior / 实际行为

The ui looks gray instead of black
The rest of the app is fine only the illustration page

### Other details / 其它细节

The problem only appears in old ui the new ui is fine
Only v4.1.1 and above have the problem

**Comment by CeuiLiSA** [comment]
fixed in the latest release

**Comment by nobSEIFO** [comment]
> fixed in the latest release

**gif**  details page : fixed ✔️
**Illustration** details : still not ❌

https://imgur.com/a/UYMYuHi
